name: 'Simple File Upload'
description: 'Perform a simple file transfer using FTP.'
author: 'Zachary Cardoza'
inputs:
  user:
    description: 'FTP User'
    required: true
  password:
    description: 'FTP Password'
    required: true
  host:
    description: 'FTP Hostname'
    required: true
  port:
    description: 'FTP Hostname'
    required: false
    default: '21'
  src: 
    description: 'Path to file to upload'
    required: true
  dest: 
    description: 'Destination file path on FTP remote'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload'  
  color: 'yellow'
