name: 'Simple File Upload'
description: 'Perform a simple file transfer using FTP.'
author: 'Zachary Cardoza'
inputs:
  user:
    description: 'FTP User'
    required: true
  password:
    description: 'FTP Password'
    required: true
  host:
    description: 'FTP Hostname'
    required: true
  port:
    description: 'FTP Hostname'
    required: false
    default: '21'
  secure:
    description: 'Should use FTPS?'
    required: false
    default: false
  src: 
    description: 'Path to file(s) to upload (can be a glob)'
    required: true
  dest: 
    description: 'Destination path on FTP remote'
    required: true
  verbose:
    description: 'Should output verbose logs?'
    required: false
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'upload'  
  color: 'yellow'
